version: "1"

services:
  application:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - "./app:/usr/src/app/app"
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"